### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pinicius**
I don't understand why I cannot make this pull request. Can you explain me?
Thanks

### CODE REVIEW

**Comment by pinicius** [comment]
I've understood it --> Permissions ;)

**Comment by shem8** [comment]
Thanks, can you just fix the conflicts first?

**Comment by pinicius** [comment]
Don't know what conflicts are. I've tried to merge into my local master branch and no problem.
Any recommendation?

**Comment by shem8** [comment]
Pay attention that you work on _develop_ branch, so pull this branch, fix the conflicts on `build.gradle` file and then push.

**Comment by pinicius** [comment]
Sorry but I don't understand you. I've made pull request into _develop_ branch as it can see from the start. I'm wrong?

**Comment by shem8** [comment]
No, that's great, it's just that looks like your develop branch is out of date.

What you can do is just check out my repository (currently you're using your forked repository) from here:
https://github.com/shem8/MaterialLogin.git

Commit your changes on develop branch, and open a new pull request.

**Pull request closed without merging**
