### PR TITLE
Optimaze layout

### PR DESCRIPTION
**Pull request by StefMa**
Extract the whole login_window and register_window (it's your naming - not mine :smile_cat:) to it's own files and include these in the login_view.xml.

It's just for a better overview...

### CODE REVIEW

**Comment by StefMa** [comment]
now it compiles :+1:

**Comment by shem8** [comment]
Sorry, that's what happen when you write "material" 100 times an hour =)
Can you please also include the fix in the example app [colors.xml](https://github.com/shem8/MaterialLogin/blob/master/app/src/main/res/values/colors.xml)? I will do it in the Readme

Thanks!

**Comment by StefMa** [comment]
I've done it actually for booth.

**Comment by shem8** [comment]
Wow, great minds =)

Thanks for you help, Approved.

**Pull request merged**
