### PR TITLE
Feature/pre 21 support

### PR DESCRIPTION
**Pull request by shem8**
Use the [CircularReveal lib](https://github.com/ozodrukh/CircularReveal) for pre Lolipop support

### CODE REVIEW

**Comment by reustonium** [comment]
wow, this is great!  Thanks for adding this support.

**Comment by shem8** [comment]
Can you please test it, I don't have pre-lolipop device around here =)

**Comment by reustonium** [comment]
Here it is running on a Jellybean emulator (api16).  Looks good, but the FAB for registering might be a tad too close to the 'X' for going back to the login view.

material_login

**Comment by drduan** [comment]
great!! get

**Comment by reustonium** [comment]
After looking at this running on API23, it appears that the "register" FAB should not be visible on the register view.  

Looking at the gif above you can see that it's still visible.

**Comment by shem8** [comment]
Can't think of a reason why the FAB animation will be disabled on api 16 =\
Can you please open a bug so it will be easier to follow?

Thanks.

**Pull request merged**
